name: Validate commit

on: [pull_request]

jobs:
  gradle:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: "checkout pipeline-dsl-seed"
      uses: actions/checkout@v2
      with:
        path: 'pipeline-dsl-seed'
    - name: "checkout pipeline-dsl-seed-dep"
      uses: actions/checkout@v2
      with:
        repository: stchar/pipeline-dsl-seed-dep
        path: 'pipeline-dsl-seed-dep'
        # ref: ref
    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'zulu'
        cache: gradle
    - name: Build with Gradle
      continue-on-error: true
      uses: gradle/gradle-build-action@v1
      with:
        build-root-directory: 'pipeline-dsl-seed'
        distributions-cache-enabled: true
        dependencies-cache-enabled: true
        configuration-cache-enabled: true
        arguments: getjobs check