name: Validate commit

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: "checkout pipeline-dsl-seed"
      uses: actions/checkout@v2
      with:
        path: 'pipeline-dsl-seed'
    - name: "checkout pipeline-dsl-seed-dep"
      uses: actions/checkout@v2
      with:
        repository: stchar/pipeline-dsl-seed-dep
        path: 'pipeline-dsl-seed-dep'
        # ref: ref
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: |
        cd pipeline-dsl-seed
        chmod +x ./gradlew
        ./gradlew --no-daemon getjobs check